FROM sd2e/reactors:python2-edge
# FROM sd2e/reactors:python2

# reactor.py, config.yml, and message.jsonschema will be automatically
# added to the container when you run docker build or abaco deploy
